# Generated by Django 5.1.6 on 2025-03-11 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_userprofile_attack_userprofile_base_attack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_regen',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
