# Generated by Django 5.1.6 on 2025-03-11 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_userprofile_last_regen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_regen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
