# Generated by Django 5.1.6 on 2025-05-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_userprofile_last_regen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_stamina',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stamina',
            field=models.IntegerField(default=10),
        ),
    ]
