# Generated by Django 5.1.6 on 2025-05-19 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_userprofile_max_stamina_userprofile_stamina'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_regen_stm',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
