# Generated by Django 5.1.6 on 2025-06-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_userprofile_last_regen_stm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='base_constitution',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='base_dexterity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='base_intelligence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='base_strength',
            field=models.IntegerField(default=1),
        ),
    ]
