# Generated by Django 5.1.6 on 2025-06-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_userprofile_base_constitution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='attack',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='base_attack',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='base_defence',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='defence',
            field=models.IntegerField(default=3),
        ),
    ]
