# Generated by Django 5.1.6 on 2025-06-05 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('items', '0002_remove_item_drop_chance_item_dmg_item_dmg_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='type',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
