# Generated by Django 5.1.6 on 2025-06-05 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def fill_missing_users(apps, schema_editor):
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    User = apps.get_model("auth", "User")

    default_user = User.objects.first()
    if default_user:
        InventoryItem.objects.filter(user__isnull=True).update(user=default_user)

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventoryitem_name_remove_inventoryitem_type_and_more'),
        ('items', '0002_remove_item_drop_chance_item_dmg_item_dmg_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
