# Generated by Django 5.1.6 on 2025-04-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='test_object', max_length=25)),
                ('lvl', models.IntegerField(default=1)),
                ('base_strenght', models.IntegerField(default=1)),
                ('base_intelect', models.IntegerField(default=1)),
                ('base_dexterity', models.IntegerField(default=1)),
                ('base_constitution', models.IntegerField(default=1)),
                ('gold_drop', models.IntegerField(default=0)),
                ('base_hp', models.IntegerField(default=100)),
                ('base_attack', models.IntegerField(default=0)),
                ('base_defence', models.IntegerField(default=0)),
            ],
        ),
    ]
