# Generated by Django 5.1.6 on 2025-04-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokacje', '0002_alter_enemy_id_alter_enemy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
