# Generated by Django 5.1.6 on 2025-04-01 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokacje', '0003_alter_enemy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enemy',
            name='description',
            field=models.TextField(blank=True, default='Opis przeciwnika'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='type',
            field=models.CharField(choices=[('normal', 'Normalny'), ('elite', 'Elita'), ('boss', 'Boss')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='enemy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
