# Generated by Django 5.1.6 on 2025-04-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokacje', '0004_enemy_created_at_enemy_description_enemy_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test_location', max_length=25)),
                ('enemies', models.ManyToManyField(related_name='locations', to='lokacje.enemy')),
            ],
        ),
    ]
