# Generated by Django 5.1.6 on 2025-05-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokacje', '0005_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='lvl',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
