# Generated by Django 5.1.6 on 2025-06-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_drop_chance_item_dmg_item_dmg_max_and_more'),
        ('lokacje', '0006_alter_enemy_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='loot_table',
            field=models.ManyToManyField(blank=True, to='items.item'),
        ),
    ]
