# Generated by Django 5.1.6 on 2025-06-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_drop_chance_item_dmg_item_dmg_max_and_more'),
        ('lokacje', '0007_enemy_loot_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='drop_chance',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=3),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='loot_table',
            field=models.ManyToManyField(blank=True, related_name='loot_table', to='items.item'),
        ),
    ]
