# Generated by Django 5.1.6 on 2025-06-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokacje', '0008_enemy_drop_chance_alter_enemy_loot_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='portrait',
            field=models.ImageField(blank=True, help_text='Portret wroga', null=True, upload_to='portraits/'),
        ),
    ]
