# Generated by Django 5.1.6 on 2025-06-06 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_remove_item_drop_chance_item_dmg_item_dmg_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('available_until', models.DateTimeField()),
                ('type', models.CharField(choices=[('blacksmith', 'Kowal'), ('alchemist', 'Alchemik')], max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
