# Generated by Django 5.1.6 on 2025-06-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantoffer',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
