# Generated by Django 5.1.6 on 2025-05-20 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
