# Generated by Django 5.1.6 on 2025-05-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('merchant', '0002_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Opis kupca'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='inventory',
            field=models.ManyToManyField(blank=True, default=None, help_text='Przedmioty dostępne u kupca', to='items.item'),
        ),
    ]
