# Generated by Django 5.1.6 on 2025-05-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa przedmiotu', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Opis przedmiotu')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', help_text='Rzadkość przedmiotu', max_length=50)),
                ('slot', models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('legs', 'Legs'), ('feet', 'Feet'), ('hands', 'Hands'), ('weapon', 'Weapons'), ('shield', 'Shield'), ('accessory', 'Accessory')], help_text='Slot, do którego pasuje przedmiot', max_length=50)),
                ('item_level', models.IntegerField(help_text='Poziom przedmiotu(ilvl)')),
                ('drop_chance', models.FloatField(help_text='Szansa na drop w procentach')),
                ('value', models.IntegerField(default=0, help_text='Wartość przedmiotu')),
            ],
        ),
    ]
