# Generated by Django 5.1.6 on 2025-05-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='drop_chance',
        ),
        migrations.AddField(
            model_name='item',
            name='dmg',
            field=models.IntegerField(default=0, help_text='Obrażenia przedmiotu'),
        ),
        migrations.AddField(
            model_name='item',
            name='dmg_max',
            field=models.IntegerField(default=0, help_text='Maksymalne obrażenia przedmiotu'),
        ),
        migrations.AddField(
            model_name='item',
            name='dmg_min',
            field=models.IntegerField(default=0, help_text='Minimalne obrażenia przedmiotu'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_constitution',
            field=models.IntegerField(default=0, help_text='Wytrzymałość przedmiotu'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_dexterity',
            field=models.IntegerField(default=0, help_text='Zręczność przedmiotu'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_intelligence',
            field=models.IntegerField(default=0, help_text='Inteligencja przedmiotu'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_strength',
            field=models.IntegerField(default=0, help_text='Siła przedmiotu'),
        ),
    ]
