# Generated by Django 5.1.6 on 2025-06-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_drop_chance_item_dmg_item_dmg_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='effect_value',
            field=models.IntegerField(blank=True, help_text='Wartość efektu (np. HP +50)', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('equipment', 'Ekwipunek'), ('potion_hp', 'Mikstura HP'), ('potion_stamina', 'Mikstura Staminy')], default='equipment', help_text='Typ przedmiotu', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_level',
            field=models.IntegerField(help_text='Poziom przedmiotu (ilvl)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot',
            field=models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('legs', 'Legs'), ('feet', 'Feet'), ('hands', 'Hands'), ('weapon', 'Weapons'), ('shield', 'Shield'), ('accessory', 'Accessory'), ('none', 'Brak')], default='none', help_text='Slot, do którego pasuje przedmiot', max_length=50),
        ),
    ]
